export default {
  primaryColor: "#03498F",
  secondaryColor: "#F99D1E",
  indicatorColor: "#FFF",
  textBoxColor: "#FFF",
  shadowColor: "#000",
  buttonColor: "#4FA6DA",
  disabledButtonColor: "#9B9B9B",
  buttonFontColor: "#FFF",
  linkFontColor: "#FFF",
  linkFontColorPressed: "#F99D1E",
  disabledLinkFontColor: "#9B9B9B",
  disabledLinkFontColorPressed: "#9B9B9B",
  labelFontColor: "#FFF",
  homeBackgroundColor: "#3D3E3F",
  toolBarButtonColor: "#FFF",
  eventListSectionHeaderColor: "#D3D3D3",
  eventListRowHostnameColor: "#F99D1E",
  eventListRowProgramColor: "#4FA6DA",
  eventListRowMessageColor: "#FFF",
  actionSheetButtonFontColor: "#007AFF",
  actionSheetOptionBorderColor: "#DADADE",
  actionSheetOptionFontColor: "#007AFF",
  actionSheetTitleFontColor: "#030303",
  actionSheetTextBoxFontColor: "#030303",
  actionSheetTextBoxBorderColor: "#DADADE"
}